use_frameworks!

platform :ios, '11.0'

target 'BYCSegmentView_Example' do
  pod 'BYCSegmentView', :path => '../'
  pod 'JXSegmentedView', '~> 1.2.7'
  pod 'MJRefresh'
  pod 'SnapKit', '5.0.1'
  pod 'BYCRefresh'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'WRNavigationBar','~>1.4.0'
end
